// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/c2fo/releasegen/internal/vcs"
	mock "github.com/stretchr/testify/mock"
)

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

type Repo_Expecter struct {
	mock *mock.Mock
}

func (_m *Repo) EXPECT() *Repo_Expecter {
	return &Repo_Expecter{mock: &_m.Mock}
}

// AllChangelogPaths provides a mock function for the type Repo
func (_mock *Repo) AllChangelogPaths(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllChangelogPaths")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repo_AllChangelogPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllChangelogPaths'
type Repo_AllChangelogPaths_Call struct {
	*mock.Call
}

// AllChangelogPaths is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repo_Expecter) AllChangelogPaths(ctx interface{}) *Repo_AllChangelogPaths_Call {
	return &Repo_AllChangelogPaths_Call{Call: _e.mock.On("AllChangelogPaths", ctx)}
}

func (_c *Repo_AllChangelogPaths_Call) Run(run func(ctx context.Context)) *Repo_AllChangelogPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repo_AllChangelogPaths_Call) Return(strings []string, err error) *Repo_AllChangelogPaths_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Repo_AllChangelogPaths_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *Repo_AllChangelogPaths_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTagAndPush provides a mock function for the type Repo
func (_mock *Repo) CommitTagAndPush(ctx context.Context, opts vcs.CommitTagPushOptions) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CommitTagAndPush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, vcs.CommitTagPushOptions) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repo_CommitTagAndPush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTagAndPush'
type Repo_CommitTagAndPush_Call struct {
	*mock.Call
}

// CommitTagAndPush is a helper method to define mock.On call
//   - ctx context.Context
//   - opts vcs.CommitTagPushOptions
func (_e *Repo_Expecter) CommitTagAndPush(ctx interface{}, opts interface{}) *Repo_CommitTagAndPush_Call {
	return &Repo_CommitTagAndPush_Call{Call: _e.mock.On("CommitTagAndPush", ctx, opts)}
}

func (_c *Repo_CommitTagAndPush_Call) Run(run func(ctx context.Context, opts vcs.CommitTagPushOptions)) *Repo_CommitTagAndPush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 vcs.CommitTagPushOptions
		if args[1] != nil {
			arg1 = args[1].(vcs.CommitTagPushOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repo_CommitTagAndPush_Call) Return(err error) *Repo_CommitTagAndPush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repo_CommitTagAndPush_Call) RunAndReturn(run func(ctx context.Context, opts vcs.CommitTagPushOptions) error) *Repo_CommitTagAndPush_Call {
	_c.Call.Return(run)
	return _c
}

// IsChangelogModifiedSinceTag provides a mock function for the type Repo
func (_mock *Repo) IsChangelogModifiedSinceTag(ctx context.Context, changelogPath string, tagName string) (bool, error) {
	ret := _mock.Called(ctx, changelogPath, tagName)

	if len(ret) == 0 {
		panic("no return value specified for IsChangelogModifiedSinceTag")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, changelogPath, tagName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, changelogPath, tagName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, changelogPath, tagName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repo_IsChangelogModifiedSinceTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsChangelogModifiedSinceTag'
type Repo_IsChangelogModifiedSinceTag_Call struct {
	*mock.Call
}

// IsChangelogModifiedSinceTag is a helper method to define mock.On call
//   - ctx context.Context
//   - changelogPath string
//   - tagName string
func (_e *Repo_Expecter) IsChangelogModifiedSinceTag(ctx interface{}, changelogPath interface{}, tagName interface{}) *Repo_IsChangelogModifiedSinceTag_Call {
	return &Repo_IsChangelogModifiedSinceTag_Call{Call: _e.mock.On("IsChangelogModifiedSinceTag", ctx, changelogPath, tagName)}
}

func (_c *Repo_IsChangelogModifiedSinceTag_Call) Run(run func(ctx context.Context, changelogPath string, tagName string)) *Repo_IsChangelogModifiedSinceTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repo_IsChangelogModifiedSinceTag_Call) Return(b bool, err error) *Repo_IsChangelogModifiedSinceTag_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Repo_IsChangelogModifiedSinceTag_Call) RunAndReturn(run func(ctx context.Context, changelogPath string, tagName string) (bool, error)) *Repo_IsChangelogModifiedSinceTag_Call {
	_c.Call.Return(run)
	return _c
}

// ReachableTags provides a mock function for the type Repo
func (_mock *Repo) ReachableTags(ctx context.Context) ([]vcs.TagInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReachableTags")
	}

	var r0 []vcs.TagInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]vcs.TagInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []vcs.TagInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]vcs.TagInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repo_ReachableTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReachableTags'
type Repo_ReachableTags_Call struct {
	*mock.Call
}

// ReachableTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repo_Expecter) ReachableTags(ctx interface{}) *Repo_ReachableTags_Call {
	return &Repo_ReachableTags_Call{Call: _e.mock.On("ReachableTags", ctx)}
}

func (_c *Repo_ReachableTags_Call) Run(run func(ctx context.Context)) *Repo_ReachableTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repo_ReachableTags_Call) Return(tagInfos []vcs.TagInfo, err error) *Repo_ReachableTags_Call {
	_c.Call.Return(tagInfos, err)
	return _c
}

func (_c *Repo_ReachableTags_Call) RunAndReturn(run func(ctx context.Context) ([]vcs.TagInfo, error)) *Repo_ReachableTags_Call {
	_c.Call.Return(run)
	return _c
}
