// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/c2fo/releasegen/internal/forge"
	mock "github.com/stretchr/testify/mock"
)

// NewReleaser creates a new instance of Releaser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReleaser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Releaser {
	mock := &Releaser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Releaser is an autogenerated mock type for the Releaser type
type Releaser struct {
	mock.Mock
}

type Releaser_Expecter struct {
	mock *mock.Mock
}

func (_m *Releaser) EXPECT() *Releaser_Expecter {
	return &Releaser_Expecter{mock: &_m.Mock}
}

// CreateRelease provides a mock function for the type Releaser
func (_mock *Releaser) CreateRelease(ctx context.Context, opts forge.CreateReleaseOptions) error {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateRelease")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, forge.CreateReleaseOptions) error); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Releaser_CreateRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRelease'
type Releaser_CreateRelease_Call struct {
	*mock.Call
}

// CreateRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - opts forge.CreateReleaseOptions
func (_e *Releaser_Expecter) CreateRelease(ctx interface{}, opts interface{}) *Releaser_CreateRelease_Call {
	return &Releaser_CreateRelease_Call{Call: _e.mock.On("CreateRelease", ctx, opts)}
}

func (_c *Releaser_CreateRelease_Call) Run(run func(ctx context.Context, opts forge.CreateReleaseOptions)) *Releaser_CreateRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 forge.CreateReleaseOptions
		if args[1] != nil {
			arg1 = args[1].(forge.CreateReleaseOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Releaser_CreateRelease_Call) Return(err error) *Releaser_CreateRelease_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Releaser_CreateRelease_Call) RunAndReturn(run func(ctx context.Context, opts forge.CreateReleaseOptions) error) *Releaser_CreateRelease_Call {
	_c.Call.Return(run)
	return _c
}
